version: "2"

run:
  timeout: 5m

formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true

linters:
  default: none
  enable:
    - govet          # suspicious constructs
    - errcheck       # unchecked errors
    - staticcheck    # advanced static analysis (includes gosimple checks)
    - ineffassign    # useless assignments
    - unused         # unused code
    - gosec          # security issues
  settings:
    errcheck:
      check-blank: true
