run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - gofmt          # canonical formatting
    - govet          # suspicious constructs
    - errcheck       # unchecked errors
    - staticcheck    # advanced static analysis
    - gosimple       # simplifiable code
    - ineffassign    # useless assignments
    - unused         # unused code
    - gosec          # security issues

linters-settings:
  gofmt:
    simplify: true
  errcheck:
    check-blank: true
