version: "2"

run:
  timeout: 5m

formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true

linters:
  # v2: Use 'standard', 'all', or 'fast' [2]
  default: standard 
  enable:
    - asasalint
    - asciicheck
    - contextcheck
    - dogsled
    - errcheck
    - dupl
    - dupword
    - misspell
  disable:
    - gochecknoglobals

issues:
  max-same-issues: 0