version: "2"

run:
  timeout: 5m

formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true

linters:
  # v2: Use 'standard', 'all', or 'fast' [2]
  default: standard 
  enable:
    - asasalint
    - asciicheck
    - contextcheck
    - dogsled
    - errcheck
    - dupl
    - dupword
    - misspell
  disable:
    - gochecknoglobals

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

issues:
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck